name: Test on crates

on:
  push:
    branches: 'master'
  pull_request:
    branches: [ '**' ]

env:
  RUST_BACKTRACE: 1

jobs:
  # Test `cargo-prusti` on a collection of crates.
  test-crates:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Setup Rust
        uses: actions-rs/toolchain@v1.0.6
      - name: Set up the environment
        run: python x.py setup
      - name: Build with cargo --release
        run: python x.py build --release --all --verbose
      - name: Test Prusti on a collection of crates
        run: ./target/release/test-crates
